#ifndef PLAYGROUND_PLAY_MACRO_H_
#define PLAYGROUND_PLAY_MACRO_H_

#define PLAYGROUND_VERSION v_0_0_20260310

#define PLAYGROUND_NAMESPACE playground

#define PLAYGROUND_NAMESPACE_INLINE_START \
    inline namespace PLAYGROUND_VERSION   \
    {

#define PLAYGROUND_NAMESPACE_INLINE_END }

#endif // PLAYGROUND_PLAY_MACRO_H_
